{"name": "Valid user logs in", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Locator.fill: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"input[data-test='username']\")\n\n", "trace": "  File \"/usr/local/lib/python3.12/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.12/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/app/features/steps/login_steps.py\", line 13, in step_login\n    context.login_page.login(username, password)\n  File \"/app/pages/login_page.py\", line 13, in login\n    self.username_input.fill(username)  # Fill username\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/sync_api/_generated.py\", line 15743, in fill\n    self._sync(\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_locator.py\", line 208, in fill\n    return await self._frame.fill(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_frame.py\", line 527, in fill\n    await self._channel.send(\"fill\", locals_to_params(locals()))\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py\", line 520, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Given user opens the login page", "status": "passed", "start": 1751522769985, "stop": 1751522772017}, {"name": "When user logs in with username \"standard_user\" and password \"secret_sauce\"", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Locator.fill: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"input[data-test='username']\")\n\n", "trace": "  File \"/usr/local/lib/python3.12/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.12/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/app/features/steps/login_steps.py\", line 13, in step_login\n    context.login_page.login(username, password)\n  File \"/app/pages/login_page.py\", line 13, in login\n    self.username_input.fill(username)  # Fill username\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/sync_api/_generated.py\", line 15743, in fill\n    self._sync(\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_locator.py\", line 208, in fill\n    return await self._frame.fill(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_frame.py\", line 527, in fill\n    await self._channel.send(\"fill\", locals_to_params(locals()))\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py\", line 520, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1751522772017, "stop": 1751522802225}, {"name": "Then user should land on the products page", "status": "skipped", "start": 1751522802479, "stop": 1751522802479}], "attachments": [{"name": "Screenshot", "source": "83960945-cd31-47a8-b751-f31869edf844-attachment.png", "type": "image/png"}, {"name": "Failure Video", "source": "9d77e63c-b087-44fd-9732-602cdb389a78-attachment.mp4", "type": "video/mp4"}], "start": 1751522768008, "stop": 1751522802479, "uuid": "3f407bbe-22d6-48d3-897d-3e73836d8eff", "historyId": "08ddf9e91e5f4334dee38d80120e896a", "fullName": "Login to SauceDemo: Valid user logs in", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login to SauceDemo"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}